  [build]
  builder = "DOCKERFILE"
  dockerfilePath = "./Dockerfile.chromadb"

  [deploy]
  startCommand = "chromadb"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 5

  [[services]]
  name = "chromadb"
