  [build]
  builder = "NIXPACKS"
  buildCommand = "npm ci && npm run build"

  [deploy]
  startCommand = "npm start"
  healthcheckPath = "/"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 5

  [[services]]
  name = "mcp-server"
