  [build]
  builder = "NIXPACKS"
  buildCommand = "npm ci && npx prisma generate && npm run build"

  [deploy]
  startCommand = "npx prisma migrate deploy && npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 5

  [[services]]
  name = "api"
